In [2]:
import nsepy as nse
from datetime import date

In [9]:
start = date(2022,12,26)
end = date.today()
stock = nse.get_history("RELIANCE",start=start,end=end)
stock.columns

Index(['Symbol', 'Series', 'Prev Close', 'Open', 'High', 'Low', 'Last',
       'Close', 'VWAP', 'Volume', 'Turnover', 'Trades', 'Deliverable Volume',
       '%Deliverble'],
      dtype='object')

In [10]:
stock

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2022-12-26,RELIANCE,EQ,2502.2,2514.75,2542.0,2492.4,2525.0,2524.05,2523.81,2764496,6.977059e+14,117927,1225057,0.4431

In [22]:
stocks = nse.get_quote("LT")
stocks

{'tradedDate': '27DEC2022',
 'data': [{'pricebandupper': '2,300.15',
   'symbol': 'LT',
   'applicableMargin': '13.43',
   'bcEndDate': '-',
   'totalSellQuantity': '-',
   'adhocMargin': '-',
   'companyName': 'Larsen & Toubro Limited',
   'marketType': 'N',
   'exDate': '21-JUL-22',
   'bcStartDate': '-',
   'css_status_desc': 'Listed',
   'dayHigh': '2,128.00',
   'basePrice': '2,091.05',
   'securityVar': '9.93',
   'pricebandlower': '1,881.95',
   'sellQuantity5': '-',
   'sellQuantity4': '-',
   'sellQuantity3': '-',
   'cm_adj_high_dt': '16-DEC-22',
   'sellQuantity2': '-',
   'dayLow': '2,085.00',
   'sellQuantity1': '-',
   'quantityTraded': '10,59,351',
   'pChange': '1.43',
   'totalTradedValue': '22,363.22',
   'deliveryToTradedQuantity': '50.58',
   'totalBuyQuantity': '209',
   'averagePrice': '2,111.03',
   'indexVar': '-',
   'cm_ffm': '2,56,689.93',
   'purpose': 'DIVIDEND - RS 22 PER SHARE',
   'buyPrice2': '-',
   'secDate': '27-Dec-2022 00:00:00',
   'buyPrice1': '2,124.10',
   'high52': '2,211.60',
   'previousClose': '2,091.05',
   'ndEndDate': '-',
   'low52': '1,456.35',
   'buyPrice4': '-',
   'buyPrice3': '-',
   'recordDate': '22-JUL-22',
   'deliveryQuantity': '5,35,807',
   'buyPrice5': '-',
   'priceBand': 'No Band',
   'extremeLossMargin': '3.50',
   'cm_adj_low_dt': '20-JUN-22',
   'varMargin': '9.93',
   'sellPrice1': '-',
   'sellPrice2': '-',
   'totalTradedVolume': '10,59,351',
   'sellPrice3': '-',
   'sellPrice4': '-',
   'sellPrice5': '-',
   'change': '29.95',
   'surv_indicator': '-',
   'ndStartDate': '-',
   'buyQuantity4': '-',
   'isExDateFlag': False,
   'buyQuantity3': '-',
   'buyQuantity2': '-',
   'buyQuantity1': '209',
   'series': 'EQ',
   'faceValue': '2.00',
   'buyQuantity5': '-',
   'closePrice': '0.00',
   'open': '2,101.55',
   'isinCode': 'INE018A01030',
   'lastPrice': '2,121.00'}],
 'optLink': '/marketinfo/sym_map/symbolMapping.jsp?symbol=LT&instrument=-&date=-&segmentLink=17&symbolCount=2',
 'otherSeries': ['EQ'],
 'futLink': '/live_market/dynaContent/live_watch/get_quote/GetQuoteFO.jsp?underlying=LT&instrument=FUTSTK&expiry=27DEC2022&type=-&strike=-',
 'lastUpdateTime': '27-DEC-2022 16:00:19'}

In [29]:
# options
rel = nse.get_history(symbol="RELIANCE", start=date(2022,12,1), end=date(2022,12,30), index=False,option_type="CE", strike_price=2100, expiry_date=date(2022,12,29))
rel

,Symbol,Expiry,Option Type,Strike Price,Open,High,Low,Close,Last,Settle Price,Number of Contracts,Turnover,Premium Turnover,Open Interest,Change in OI,Underlying
Date,,,,,,,,,,,,,,,,
2022-12-01,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,633.80,0,0.0,0.0,2000,0,2723.30
2022-12-02,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,632.30,0,0.0,0.0,2000,0,NaN
2022-12-05,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,591.45,0,0.0,0.0,2000,0,NaN
2022-12-06,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,598.80,0,0.0,0.0,2000,0,NaN
2022-12-07,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,558.95,0,0.0,0.0,2000,0,2650.50
2022-12-08,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,557.30,0,0.0,0.0,2000,0,NaN
2022-12-09,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,516.85,0,0.0,0.0,2000,0,NaN
2022-12-12,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,519.60,0,0.0,0.0,2000,0,2613.10
2022-12-13,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,531.10,0,0.0,0.0,2000,0,NaN
2022-12-14,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,521.25,0,0.0,0.0,2000,0,2615.50
2022-12-15,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,483.75,0,0.0,0.0,2000,0,NaN
2022-12-16,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,470.65,0,0.0,0.0,2000,0,2565.60
2022-12-19,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,477.0,477.0,503.20,0,0.0,0.0,2000,0,2599.30
2022-12-20,RELIANCE,2022-12-29,CE,2100.0,515.0,515.0,515.0,515.0,515.0,525.30,1,654000.0,129000.0,2250,250,2621.80
2022-12-21,RELIANCE,2022-12-29,CE,2100.0,0.0,0.0,0.0,515.0,515.0,487.65,0,0.0,0.0,2250,0,2584.50
2022-12-22,RELIANCE,2022-12-29,CE,2100.0,500.0,500.0,488.2,488.2,488.2,480.55,5,3242000.0,617000.0,1000,-1250,NaN
2022-12-23,RELIANCE,2022-12-29,CE,2100.0,475.0,475.0,460.0,460.0,460.0,404.50,2,1284000.0,234000.0,500,-500,NaN
2022-12-26,RELIANCE,2022-12-29,CE,2100.0,429.0,429.0,428.0,428.0,428.0,425.25,2,1264000.0,214000.0,0,-500,2524.05