In [3]:
import pandas_ta as ta 
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.DataFrame()
df = df.ta.ticker("AAPL", period="1y")
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-12-20 00:00:00-05:00,167.308974,169.595705,166.493713,168.770493,107499100,0.0,0
2021-12-21 00:00:00-05:00,170.570034,172.200571,168.144112,171.991791,91185900,0.0,0
2021-12-22 00:00:00-05:00,172.041492,174.845227,171.156628,174.626495,92135300,0.0,0
2021-12-23 00:00:00-05:00,174.835306,175.829536,174.258651,175.262817,68356600,0.0,0
2021-12-27 00:00:00-05:00,176.068149,179.378936,176.048276,179.289459,74919600,0.0,0
...,...,...,...,...,...,...,...
2022-12-13 00:00:00-05:00,149.500000,149.970001,144.240005,145.470001,93886200,0.0,0
2022-12-14 00:00:00-05:00,145.350006,146.660004,141.160004,143.210007,82291200,0.0,0
2022-12-15 00:00:00-05:00,141.110001,141.800003,136.029999,136.500000,98931900,0.0,0
2022-12-16 00:00:00-05:00,136.690002,137.649994,133.729996,134.509995,160080100,0.0,0
2022-12-19 00:00:00-05:00,135.110001,135.199997,131.320007,132.369995,79482500,0.0,0

In [26]:
df.ta.indicators()
df.ta.categories

Pandas TA - Technical Analysis Indicators - v0.3.14b0
Total Indicators & Utilities: 205
Abbreviations:
    aberration, above, above_value, accbands, ad, adosc, adx, alma, amat, ao, aobv, apo, aroon, atr, bbands, below, below_value, bias, bop, brar, cci, cdl_pattern, cdl_z, cfo, cg, chop, cksp, cmf, cmo, coppock, cross, cross_value, cti, decay, decreasing, dema, dm, donchian, dpo, ebsw, efi, ema, entropy, eom, er, eri, fisher, fwma, ha, hilo, hl2, hlc3, hma, hwc, hwma, ichimoku, increasing, inertia, jma, kama, kc, kdj, kst, kurtosis, kvo, linreg, log_return, long_run, macd, mad, massi, mcgd, median, mfi, midpoint, midprice, mom, natr, nvi, obv, ohlc4, pdist, percent_return, pgo, ppo, psar, psl, pvi, pvo, pvol, pvr, pvt, pwma, qqe, qstick, quantile, rma, roc, rsi, rsx, rvgi, rvi, short_run, sinwma, skew, slope, sma, smi, squeeze, squeeze_pro, ssf, stc, stdev, stoch, stochrsi, supertrend, swma, t3, td_seq, tema, thermo, tos_stdevall, trima, trix, true_range, tsi, tsignals, ttm_trend, ui, uo, variance, vhf, vidya, vortex, vp, vwap, vwma, wcp, willr, wma, xsignals, zlma, zscore

Candle Patterns:
    2crows, 3blackcrows, 3inside, 3linestrike, 3outside, 3starsinsouth, 3whitesoldiers, abandonedbaby, advanceblock, belthold, breakaway, closingmarubozu, concealbabyswall, counterattack, darkcloudcover, doji, dojistar, dragonflydoji, engulfing, eveningdojistar, eveningstar, gapsidesidewhite, gravestonedoji, hammer, hangingman, harami, haramicross, highwave, hikkake, hikkakemod, homingpigeon, identical3crows, inneck, inside, invertedhammer, kicking, kickingbylength, ladderbottom, longleggeddoji, longline, marubozu, matchinglow, mathold, morningdojistar, morningstar, onneck, piercing, rickshawman, risefall3methods, separatinglines, shootingstar, shortline, spinningtop, stalledpattern, sticksandwich, takuri, tasukigap, thrusting, tristar, unique3river, upsidegap2crows, xsidegap3methods

['candles',
 'cycles',
 'momentum',
 'overlap',
 'performance',
 'statistics',
 'trend',
 'volatility',
 'volume']

In [20]:
df = df.ta.ticker("RELIANCE.NS", period="1y")
CustomStrategy = ta.Strategy(
    name="CustomStrategy",
    description="A custom strategy using the Strategy class.",
    ta=[
        {"kind": "sma", "length": 50},
        {"kind": "sma", "length": 100},
        {"kind": "rsi", "length": 14},
        {"kind": "macd", "fast": 12, "slow": 26, "signal": 9},
        {"kind": "bbands", "length": 20, "std": 2},
    ]
)

df.ta.strategy(CustomStrategy)
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,SMA_50,SMA_100,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_20_2.0,BBM_20_2.0,BBU_20_2.0,BBB_20_2.0,BBP_20_2.0
Date,,,,,,,,,,,,,,,,,,
2021-12-20 00:00:00+05:30,2310.892591,2310.892591,2240.354962,2270.514160,6611376,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-21 00:00:00+05:30,2304.412053,2338.957946,2285.319390,2304.312256,5924071,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-22 00:00:00+05:30,2317.921278,2364.780198,2315.030080,2358.997803,8149415,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-23 00:00:00+05:30,2366.873881,2372.855871,2350.971808,2358.150146,4186912,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-24 00:00:00+05:30,2362.886090,2384.820054,2330.533543,2365.677734,3639616,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-14 00:00:00+05:30,2637.649902,2638.949951,2611.000000,2615.500000,3354618,0.0,0,2551.181016,2544.618735,49.219647,18.505626,-12.950323,31.455949,2524.189506,2639.902515,2755.615523,8.766461,0.394556
2022-12-15 00:00:00+05:30,2602.500000,2615.000000,2571.000000,2578.350098,4009765,0.0,0,2555.358018,2545.447368,43.215270,12.220442,-15.388405,27.608847,2521.355089,2638.867517,2756.379945,8.906277,0.242506
2022-12-16 00:00:00+05:30,2571.000000,2618.800049,2558.149902,2565.600098,7308934,0.0,0,2558.406021,2546.315000,41.350820,6.139794,-17.175243,23.315037,2516.713198,2637.265027,2757.816855,9.142185,0.202763
2022-12-19 00:00:00+05:30,2581.000000,2604.000000,2566.699951,2599.300049,3567363,0.0,0,2561.950020,2547.352134,47.765497,3.994100,-15.456749,19.450850,2524.334271,2639.685034,2755.035797,8.739737,0.324947
2022-12-20 00:00:00+05:30,2583.899902,2595.649902,2566.000000,2591.399902,2034956,0.0,0,2565.131016,2549.134788,46.482019,1.637273,-14.250861,15.888134,2528.525551,2641.002527,2753.479502,8.517748,0.279499

In [26]:
stock = input("Enter the stock ticker: ")
period = input("Enter the period: ")
df = pd.DataFrame()
df = df.ta.ticker(stock, period=period)

print("These are the following categories of indicators:")
print(df.ta.categories)

input1 = input("Enter the category of indicators you want to see: ")

cat_list = input1.split(",")
for i in cat_list:
    df.ta.strategy(i)

df

These are the following categories of indicators:
['candles', 'cycles', 'momentum', 'overlap', 'performance', 'statistics', 'trend', 'volatility', 'volume']

,Open,High,Low,Close,Volume,Dividends,Stock Splits,AO_5_34,APO_12_26,BIAS_SMA_26,...,STOCHk_14_3_3,STOCHd_14_3_3,STOCHRSIk_14_14_3_3,STOCHRSId_14_14_3_3,TRIX_30_9,TRIXs_30_9,TSI_13_25_13,TSIs_13_25_13,UO_7_14_28,WILLR_14
Date,,,,,,,,,,,,,,,,,,,,,
2021-12-20 00:00:00+05:30,2310.892591,2310.892591,2240.354962,2270.514160,6611376,0.0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-21 00:00:00+05:30,2304.412053,2338.957946,2285.319390,2304.312256,5924071,0.0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-22 00:00:00+05:30,2317.921278,2364.780198,2315.030080,2358.997803,8149415,0.0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-23 00:00:00+05:30,2366.873881,2372.855871,2350.971808,2358.150146,4186912,0.0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-24 00:00:00+05:30,2362.886090,2384.820054,2330.533543,2365.677734,3639616,0.0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-14 00:00:00+05:30,2637.649902,2638.949951,2611.000000,2615.500000,3354618,0.0,0,19.203393,36.942295,-0.006168,...,45.797114,46.299978,6.171493,5.965234,0.104863,0.088765,12.156061,20.094260,47.549723,-55.138340
2022-12-15 00:00:00+05:30,2602.500000,2615.000000,2571.000000,2578.350098,4009765,0.0,0,3.105883,26.774675,-0.019917,...,41.218722,43.989916,5.230794,5.380195,0.105787,0.093344,8.297760,18.409046,40.745237,-69.822096
2022-12-16 00:00:00+05:30,2571.000000,2618.800049,2558.149902,2565.600098,7308934,0.0,0,-8.067955,13.227556,-0.024665,...,26.274756,37.763531,1.433196,4.278494,0.105645,0.097049,4.512585,16.423837,34.172874,-96.215295
2022-12-19 00:00:00+05:30,2581.000000,2604.000000,2566.699951,2599.300049,3567363,0.0,0,-12.938402,4.144223,-0.011384,...,18.288972,28.594150,7.004771,4.556254,0.104964,0.099861,3.070845,14.516267,39.096407,-79.095694
2022-12-20 00:00:00+05:30,2583.899902,2596.850098,2566.000000,2596.500000,2127700,0.0,0,-21.430006,-5.459293,-0.012123,...,14.723630,19.762453,13.888400,7.442122,0.103793,0.101817,1.769760,12.695337,46.348841,-80.518121

In [30]:
df.ta.exchange
df.ta.exchange = "NSE"

In [32]:
df.ta.last_run

'Tuesday December 20, 2022, NYSE: 15:06:50, Local: 19:06:50 IST, Day 354/365 (97.00%)'

In [35]:
df.ta.time_range
df.ta.time_range = "days"

In [37]:
help(ta.yf)

Help on function yf in module pandas_ta.utils.data.yahoofinance:

yf(ticker: str, **kwargs)
    yf - yfinance wrapper

    It retrieves market data (ohlcv) from Yahoo Finance using yfinance.
    To install yfinance. (pip install yfinance) This method can also pull
    additional data using the 'kind' kwarg. By default kind=None and retrieves
    Historical Chart Data.

    Other options of 'kind' include:
    * All: "all"
        - Prints everything below but only returns Chart History to Pandas TA
    * Company Information: "info"
    * Institutional Holders: "institutional_holders" or "ih"
    * Major Holders: "major_holders" or "mh"
    * Mutual Fund Holders: "mutualfund_holders" or "mfh"
    * Recommendations (YTD): "recommendations" or "rec"
    * Earnings Calendar: "calendar" or "cal"
    * Earnings: "earnings" or "earn"
    * Sustainability/ESG Scores: "sustainability", "sus" or "esg"
    * Financials: "financials" or "fin"
        - Returns in order: Income Statement, Balance Sheet and Cash Flow
    * Option Chain: "option_chain" or "oc"
        - Uses the nearest expiration date by default
        - Change the expiration date using kwarg "exp"
        - Show ITM options, set kwarg "itm" to True. Or OTM options, set
        kwarg "itm" to False.
    * Chart History:
        - The only data returned to Pandas TA.

    Args:
        ticker (str): Any string for a ticker you would use with yfinance.
            Default: "SPY"
    Kwargs:
        calls (bool): When True, prints only Option Calls for the Option Chain.
            Default: None
        desc (bool): Will print Company Description when printing Company
            Information. Default: False
        exp (str): Used to print other Option Chains for the given Expiration
            Date. Default: Nearest Expiration Date for the Option Chains
        interval (str): A yfinance argument. Default: "1d"
        itm (bool): When printing Option Chains, shows ITM Options when True.
            When False, it shows OTM Options: Default: None
        kind (str): Options see above. Default: None
        period (str): A yfinance argument. Default: "max"
        proxy (dict): Proxy for yfinance to use. Default: {}
        puts (bool): When True, prints only Option Puts for the Option Chain.
            Default: None
        show (int > 0): How many last rows of Chart History to show.
            Default: None
        snd (int): How many recent Splits and Dividends to show in Company
            Information. Default: 5
        verbose (bool): Prints Company Information "info" and a Chart History
            header to the screen. Default: False

    Returns:
        Exits if the DataFrame is empty or None
        Otherwise it returns a DataFrame of the Chart History

In [43]:
rel = ta.yahoofinance.yf("LT.NS", period="1y", interval="1d")
rel

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-12-20 00:00:00+05:30,1797.975157,1806.515810,1749.101038,1776.598877,2488158,0.0,0
2021-12-21 00:00:00+05:30,1794.914374,1828.780610,1789.582628,1804.442383,2077840,0.0,0
2021-12-22 00:00:00+05:30,1804.442449,1855.784959,1804.442449,1847.343018,1692505,0.0,0
2021-12-23 00:00:00+05:30,1859.191248,1863.979900,1838.555485,1854.698730,1677127,0.0,0
2021-12-24 00:00:00+05:30,1864.868521,1864.868521,1826.608479,1835.889648,1203991,0.0,0
...,...,...,...,...,...,...,...
2022-12-14 00:00:00+05:30,2176.949951,2210.000000,2175.050049,2195.449951,1516631,0.0,0
2022-12-15 00:00:00+05:30,2196.699951,2209.000000,2173.600098,2177.550049,1323412,0.0,0
2022-12-16 00:00:00+05:30,2161.000000,2211.600098,2161.000000,2175.000000,2822390,0.0,0
2022-12-19 00:00:00+05:30,2171.000000,2187.449951,2155.050049,2184.000000,1592779,0.0,0
2022-12-20 00:00:00+05:30,2179.899902,2179.899902,2138.000000,2163.250000,1747150,0.0,0